definitions:
  main.Match:
    properties:
      awayPlayerScore:
        type: integer
      homePlayerScore:
        type: integer
      matchID:
        type: string
      name:
        type: string
      round:
        type: string
      status:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/match/{id}:
    get:
      description: Get match details by given match ID
      parameters:
      - description: Match ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Match'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Retrieve match details by match ID
      tags:
      - match
  /api/v1/matches:
    get:
      description: Get matches filtered by their status (live, completed or scheduled)
        and sorted by round
      parameters:
      - description: Match Status
        in: query
        name: status
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Match'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Retrieve matches by status
      tags:
      - matches
swagger: "2.0"
